### ISSUE TITLE
Version 0.1 [minimum features] Release

### ISSUE THREAD

**Issue by koxudaxi** [koxudaxi/poetry-pycharm-plugin#55]
Version 0.1 should support minimum features without extension points.

I would cover the common use-case in this version.
## TODO

- [x] freeze a list of features 
- [x] documentation
- [x] improve contribution guideline
- [x] test for common use-case

## Features

- [x] add a new/existing poetry environment as an interpreter
- [x] install packages with pyproject.toml when adding an interpreter
- [x] add a new pyproject.toml when it does not exists
- [x] install and import a package with poetry (QuickFix)
- [x] install packages from poetry.lock
- [x] update and lock with a popup
- [x] show a message and a link to fix settings (QuickFix)
- [x] install extras by clicking a line marker (Toml plugin is required)

### use-cases
- [x] add new poetry Interpreter with install packages from pyproject.toml
- [x] add new poetry Interpreter without install packages from pyproject.toml
- [x] add new poetry interpreter from existing enviroment
- [x] lock file from a popup after changing pyproject.toml
- [x] update file from a popup after changing pyproject.toml
- [x] install new packages from a notification after lock file is updated
- [x] install packages from action of installation (alt+enter)
